# Generated by Django 5.0.6 on 2024-05-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
