# Generated by Django 5.0.6 on 2024-05-31 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('neighborhoods', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('penalty', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/assets/fines/')),
                ('observations', models.TextField()),
                ('status', models.CharField(default='pending', max_length=255)),
                ('type', models.CharField(default='fine1', max_length=250)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='users.users')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='neighborhoods.properties')),
            ],
        ),
    ]
