# Generated by Django 5.0.6 on 2024-05-31 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('address_street', models.CharField(max_length=255)),
                ('address_number', models.IntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/assets/logos/')),
                ('administrators', models.ManyToManyField(limit_choices_to={'user_type': 'administrator'}, related_name='neighborhoods_as_admin', to='users.users')),
                ('architects', models.ManyToManyField(limit_choices_to={'user_type': 'architect'}, related_name='neighborhoods_as_architect', to='users.users')),
                ('owners', models.ManyToManyField(limit_choices_to={'user_type': 'owner'}, related_name='neighborhoods_as_owner', to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_number', models.IntegerField()),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='neighborhoods.neighborhoods')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='users.users')),
            ],
        ),
    ]
